// This file was auto-generated by scaffolding but is being written fresh here.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;
use serde::Serialize;
use sysinfo::{Disks, ProcessesToUpdate, System};
use tauri::State;
use tauri::Manager;

#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;

#[cfg(target_os = "windows")]
const CREATE_NO_WINDOW: u32 = 0x08000000;

struct SysState(Mutex<System>);

#[derive(Serialize)]
struct DiskInfo {
    name: String,
    used_gb: f64,
    total_gb: f64,
    percent: f64,
    is_ssd: bool,
}

#[derive(Serialize)]
struct HardwareInfo {
    cpu_brand: String,
    cpu_cores: usize,
    ram_total_gb: f64,
    os_name: String,
    gpu_name: String,
}

/// Detecta o hardware real da máquina uma vez (chamado ao abrir a aba Início).
#[tauri::command]
fn get_hardware_info(state: State<SysState>) -> HardwareInfo {
    let sys = state.0.lock().unwrap();
    let cpu_brand = sys
        .cpus()
        .first()
        .map(|c| c.brand().trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "Processador não identificado".to_string());

    let os_name = format!(
        "{} {}",
        System::name().unwrap_or_else(|| "Windows".to_string()),
        System::os_version().unwrap_or_default()
    );

    HardwareInfo {
        cpu_brand,
        cpu_cores: sys.cpus().len(),
        ram_total_gb: ((sys.total_memory() as f64 / 1_073_741_824.0) * 10.0).round() / 10.0,
        os_name: os_name.trim().to_string(),
        gpu_name: read_gpu_name_windows(),
    }
}

#[cfg(target_os = "windows")]
fn read_gpu_name_windows() -> String {
    // Pega o nome da primeira GPU "ativa" (status OK) reportada pelo Windows.
    // Evita listar adaptadores virtuais/desligados quando há mais de uma GPU.
    let ps_cmd = "(Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue | Where-Object { $_.Status -eq 'OK' } | Select-Object -First 1 -ExpandProperty Name)";
    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if text.is_empty() { "GPU não identificada".to_string() } else { text }
        }
        Err(_) => "GPU não identificada".to_string(),
    }
}

#[cfg(not(target_os = "windows"))]
fn read_gpu_name_windows() -> String {
    "Detecção disponível apenas no Windows".to_string()
}

#[derive(Serialize, Clone)]
struct InstalledGame {
    name: String,
    exe_path: String,
    source: String, // "steam" | "epic"
}

#[derive(Serialize)]
struct GraphicsPresetResult {
    applied: bool,
    message: String,
}

/// Normaliza um nome de jogo/pasta pra comparação solta: só letras/números minúsculas.
fn normalize_name(s: &str) -> String {
    s.chars().filter(|c| c.is_ascii_alphanumeric()).map(|c| c.to_ascii_lowercase()).collect()
}

/// Procura o GameUserSettings.ini (padrão usado pela imensa maioria dos jogos feitos
/// em Unreal Engine 4/5 — Fortnite, Ark, PUBG e centenas de outros) tentando casar
/// o nome do jogo com as pastas dentro de %LOCALAPPDATA%. Não existe um jeito
/// universal de editar gráfico de QUALQUER jogo (cada engine guarda diferente),
/// então isso só funciona pra jogos Unreal Engine — é avisado com clareza quando
/// não encontra nada, em vez de fingir que ajustou.
#[cfg(target_os = "windows")]
fn find_unreal_config(game_name: &str) -> Option<PathBuf> {
    let local_appdata = std::env::var("LOCALAPPDATA").ok()?;
    let base = PathBuf::from(local_appdata);
    let target = normalize_name(game_name);
    let entries = fs::read_dir(&base).ok()?;
    let mut best: Option<PathBuf> = None;
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() { continue; }
        let folder_name = path.file_name()?.to_string_lossy().to_string();
        let norm_folder = normalize_name(&folder_name);
        if norm_folder.is_empty() { continue; }
        let matches = norm_folder.contains(&target) || target.contains(&norm_folder);
        if !matches { continue; }
        let ini_path = path.join("Saved").join("Config").join("WindowsNoEditor").join("GameUserSettings.ini");
        if ini_path.exists() {
            best = Some(ini_path);
            break;
        }
    }
    best
}

/// Ajusta as chaves de qualidade gráfica (sg.*Quality) dentro da seção
/// [ScalabilityGroups] do GameUserSettings.ini, preservando todo o resto do
/// arquivo. Cria a chave se não existir, substitui o valor se já existir.
#[cfg(target_os = "windows")]
fn set_scalability_keys(content: &str, values: &[(&str, &str)]) -> String {
    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let section_name = "[ScalabilityGroups]";
    let mut section_start: Option<usize> = None;
    let mut section_end: usize = lines.len();
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed.eq_ignore_ascii_case(section_name) {
            section_start = Some(i);
        } else if section_start.is_some() && i > section_start.unwrap() && trimmed.starts_with('[') && trimmed.ends_with(']') {
            section_end = i;
            break;
        }
    }
    let mut remaining: Vec<(&str, &str)> = values.to_vec();
    if let Some(start) = section_start {
        for i in (start + 1)..section_end {
            for (key, val) in values {
                let prefix = format!("{key}=");
                if lines[i].to_ascii_lowercase().starts_with(&prefix.to_ascii_lowercase()) {
                    lines[i] = format!("{key}={val}");
                    remaining.retain(|(k, _)| k != key);
                }
            }
        }
        // insere as chaves que não existiam ainda, logo após o cabeçalho da seção
        let insert_at = start + 1;
        let new_lines: Vec<String> = remaining.iter().map(|(k, v)| format!("{k}={v}")).collect();
        for (offset, l) in new_lines.into_iter().enumerate() {
            lines.insert(insert_at + offset, l);
        }
    } else {
        // seção não existe: cria no fim do arquivo
        lines.push(String::new());
        lines.push(section_name.to_string());
        for (k, v) in remaining {
            lines.push(format!("{k}={v}"));
        }
    }
    lines.join("\n")
}

#[cfg(target_os = "windows")]
#[tauri::command]
fn apply_game_graphics_preset(game_name: String, preset: String) -> GraphicsPresetResult {
    let ini_path = match find_unreal_config(&game_name) {
        Some(p) => p,
        None => return GraphicsPresetResult{
            applied: false,
            message: "Não encontrei um arquivo de configuração gráfica reconhecido pra esse jogo. Isso funciona pra jogos feitos em Unreal Engine — se o jogo usa outro motor, não dá pra editar o gráfico dele com segurança daqui.".into(),
        },
    };
    let content = match fs::read_to_string(&ini_path) {
        Ok(c) => c,
        Err(e) => return GraphicsPresetResult{ applied: false, message: format!("Achei o arquivo mas não consegui ler: {e}") },
    };
    let quality = match preset.as_str() {
        "performance" => "0",
        "quality" => "3",
        _ => "2",
    };
    let keys = [
        ("sg.ViewDistanceQuality", quality),
        ("sg.AntiAliasingQuality", quality),
        ("sg.ShadowQuality", quality),
        ("sg.PostProcessQuality", quality),
        ("sg.TextureQuality", quality),
        ("sg.EffectsQuality", quality),
        ("sg.FoliageQuality", quality),
        ("sg.ShadingQuality", quality),
    ];
    let new_content = set_scalability_keys(&content, &keys);
    match fs::write(&ini_path, new_content) {
        Ok(_) => GraphicsPresetResult{ applied: true, message: format!("Configuração gráfica do jogo (Unreal Engine) ajustada em: {}", ini_path.display()) },
        Err(e) => GraphicsPresetResult{ applied: false, message: format!("Achei e li o arquivo, mas não consegui salvar (talvez o jogo esteja aberto): {e}") },
    }
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
fn apply_game_graphics_preset(game_name: String, preset: String) -> GraphicsPresetResult {
    let _ = (game_name, preset);
    GraphicsPresetResult{ applied: false, message: "Disponível só no Windows".into() }
}

#[derive(Serialize, Clone)]
struct PowerPlan {
    name: String,
    guid: String,
    active: bool,
}

/// Lista os planos de energia reais do Windows (powercfg /list) — não precisa de
/// admin só pra ler. O plano "Desempenho Máximo" só aparece aqui depois de
/// desbloqueado (ele vem oculto por padrão em quase todo Windows).
#[cfg(target_os = "windows")]
#[tauri::command]
fn list_power_plans() -> Result<Vec<PowerPlan>, String> {
    let output = Command::new("powercfg")
        .args(["/list"])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .map_err(|e| format!("Não consegui listar os planos: {e}"))?;
    let text = String::from_utf8_lossy(&output.stdout);
    let mut plans = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if !line.to_lowercase().starts_with("power scheme guid:") { continue; }
        // formato: Power Scheme GUID: <guid>  (Nome do plano) [*]
        let after_guid = &line[line.find(':').map(|i| i + 1).unwrap_or(0)..].trim();
        let guid_end = after_guid.find(char::is_whitespace).unwrap_or(after_guid.len());
        let guid = after_guid[..guid_end].trim().to_string();
        let name = after_guid.get(guid_end..)
            .unwrap_or("")
            .trim()
            .trim_start_matches('(')
            .trim_end_matches('*')
            .trim_end_matches(')')
            .trim()
            .to_string();
        let active = line.trim_end().ends_with('*');
        if !guid.is_empty() {
            plans.push(PowerPlan { name: if name.is_empty() { "Plano sem nome".into() } else { name }, guid, active });
        }
    }
    Ok(plans)
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
fn list_power_plans() -> Result<Vec<PowerPlan>, String> {
    Ok(Vec::new())
}

/// Detecta jogos realmente instalados na máquina (sem precisar de admin, só leitura):
/// olha as bibliotecas da Steam (libraryfolders.vdf + appmanifest_*.acf), os
/// manifestos da Epic Games, as chaves de instalação da Ubisoft Connect no registro,
/// e a pasta padrão de instalação da Rockstar Games Launcher.
/// Não inventa jogo — só lista o que achou de fato.
#[tauri::command]
fn scan_installed_games() -> Vec<InstalledGame> {
    let mut games = scan_steam_games();
    games.extend(scan_epic_games());
    games.extend(scan_ubisoft_games());
    games.extend(scan_rockstar_games());
    games
}

#[cfg(target_os = "windows")]
fn reg_query_value(key: &str, value: &str) -> Option<String> {
    let output = Command::new("reg")
        .args(["query", key, "/v", value])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&output.stdout);
    for line in text.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with(value) {
            for ty in ["REG_SZ", "REG_DWORD", "REG_EXPAND_SZ", "REG_BINARY", "REG_QWORD", "REG_MULTI_SZ"] {
                if let Some(idx) = line.find(ty) {
                    return Some(line[idx + ty.len()..].trim().to_string());
                }
            }
        }
    }
    None
}

/// Lista as subchaves diretas de uma chave do registro (sem valores).
/// Usado pra enumerar cada jogo instalado pela Ubisoft Connect, um por subchave.
#[cfg(target_os = "windows")]
fn reg_list_subkeys(key: &str) -> Vec<String> {
    let output = Command::new("reg")
        .args(["query", key])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
    let mut result = Vec::new();
    if let Ok(o) = output {
        let text = String::from_utf8_lossy(&o.stdout);
        for line in text.lines() {
            let line = line.trim();
            if line.to_uppercase().starts_with("HKEY") && !line.eq_ignore_ascii_case(key) {
                result.push(line.to_string());
            }
        }
    }
    result
}

#[cfg(target_os = "windows")]
fn scan_ubisoft_games() -> Vec<InstalledGame> {
    let mut result = Vec::new();
    let bases = [
        r"HKLM\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs",
        r"HKLM\SOFTWARE\Ubisoft\Launcher\Installs",
    ];
    for base in bases {
        for subkey in reg_list_subkeys(base) {
            if let Some(install_dir) = reg_query_value(&subkey, "InstallDir") {
                let dir = PathBuf::from(install_dir.trim());
                if let Some(exe) = find_main_exe(&dir) {
                    let name = dir.file_name()
                        .map(|n| n.to_string_lossy().to_string())
                        .unwrap_or_else(|| "Jogo Ubisoft".to_string());
                    if !result.iter().any(|g: &InstalledGame| g.exe_path == exe) {
                        result.push(InstalledGame { name, exe_path: exe, source: "ubisoft".to_string() });
                    }
                }
            }
        }
    }
    result
}

/// A Rockstar Games Launcher não expõe uma chave de registro única e confiável
/// listando todos os jogos instalados (varia por título). Por isso, aqui a gente
/// procura direto na pasta padrão onde ela instala os jogos — funciona pra quem
/// não mudou o local de instalação, que é o caso da grande maioria.
#[cfg(target_os = "windows")]
fn scan_rockstar_games() -> Vec<InstalledGame> {
    let mut result = Vec::new();
    let bases = [std::env::var("ProgramFiles").ok(), std::env::var("ProgramFiles(x86)").ok()];
    for pf in bases.into_iter().flatten() {
        let dir = Path::new(&pf).join("Rockstar Games");
        let entries = match fs::read_dir(&dir) { Ok(e) => e, Err(_) => continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() { continue; }
            let lower = path.file_name().unwrap_or_default().to_string_lossy().to_lowercase();
            if lower.contains("launcher") || lower.contains("social club") { continue; }
            if let Some(exe) = find_main_exe(&path) {
                let name = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_else(|| "Jogo Rockstar".to_string());
                result.push(InstalledGame { name, exe_path: exe, source: "rockstar".to_string() });
            }
        }
    }
    result
}

#[cfg(target_os = "windows")]
fn scan_steam_games() -> Vec<InstalledGame> {
    let mut result = Vec::new();
    let steam_path = reg_query_value(r"HKCU\Software\Valve\Steam", "SteamPath")
        .or_else(|| reg_query_value(r"HKLM\SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath"));
    let steam_path = match steam_path {
        Some(p) => p.replace('/', "\\"),
        None => return result,
    };

    let mut libraries = vec![PathBuf::from(&steam_path)];
    let vdf_path = Path::new(&steam_path).join("steamapps").join("libraryfolders.vdf");
    if let Ok(content) = fs::read_to_string(&vdf_path) {
        for line in content.lines() {
            let line = line.trim();
            if line.starts_with("\"path\"") {
                if let Some(val) = extract_vdf_value(line) {
                    let p = PathBuf::from(val.replace("\\\\", "\\"));
                    if !libraries.contains(&p) { libraries.push(p); }
                }
            }
        }
    }

    for lib in libraries {
        let steamapps = lib.join("steamapps");
        let entries = match fs::read_dir(&steamapps) { Ok(e) => e, Err(_) => continue };
        for entry in entries.flatten() {
            let fname = entry.file_name().to_string_lossy().to_string();
            if !fname.starts_with("appmanifest_") || !fname.ends_with(".acf") { continue; }
            let content = match fs::read_to_string(entry.path()) { Ok(c) => c, Err(_) => continue };
            let mut name = None;
            let mut installdir = None;
            for line in content.lines() {
                let line = line.trim();
                if line.starts_with("\"name\"") { name = extract_vdf_value(line); }
                if line.starts_with("\"installdir\"") { installdir = extract_vdf_value(line); }
            }
            if let (Some(name), Some(installdir)) = (name, installdir) {
                let game_dir = steamapps.join("common").join(&installdir);
                if let Some(exe) = find_main_exe(&game_dir) {
                    result.push(InstalledGame { name, exe_path: exe, source: "steam".to_string() });
                }
            }
        }
    }
    result
}

#[cfg(target_os = "windows")]
fn extract_vdf_value(line: &str) -> Option<String> {
    let parts: Vec<&str> = line.split('"').filter(|s| !s.trim().is_empty()).collect();
    parts.get(1).map(|s| s.to_string())
}

#[cfg(target_os = "windows")]
fn find_main_exe(dir: &Path) -> Option<String> {
    if !dir.is_dir() { return None; }
    let ignore = ["unins", "redist", "vcredist", "dotnet", "crashpad", "crashhandler",
                  "easyanticheat", "battleye", "setup", "directx", "prereq", "vc_redist",
                  "helper", "updater", "cef", "dxwebsetup"];
    let mut best: Option<(PathBuf, u64)> = None;
    let mut stack = vec![dir.to_path_buf()];
    let mut depth = 0;
    while let Some(d) = stack.pop() {
        depth += 1;
        if depth > 60 { break; } // limite de segurança, evita ficar preso em pastas gigantes
        let entries = match fs::read_dir(&d) { Ok(e) => e, Err(_) => continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if stack.len() < 200 { stack.push(path); }
                continue;
            }
            let ext_ok = path.extension().map(|e| e.eq_ignore_ascii_case("exe")).unwrap_or(false);
            if !ext_ok { continue; }
            let lower = path.file_name().unwrap_or_default().to_string_lossy().to_lowercase();
            if ignore.iter().any(|kw| lower.contains(kw)) { continue; }
            if let Ok(meta) = entry.metadata() {
                let size = meta.len();
                if best.as_ref().map(|(_, s)| size > *s).unwrap_or(true) {
                    best = Some((path, size));
                }
            }
        }
    }
    best.map(|(p, _)| p.to_string_lossy().to_string())
}

#[cfg(target_os = "windows")]
fn scan_epic_games() -> Vec<InstalledGame> {
    let mut result = Vec::new();
    let program_data = std::env::var("PROGRAMDATA").unwrap_or_else(|_| "C:\\ProgramData".to_string());
    let manifests_dir = Path::new(&program_data).join("Epic").join("EpicGamesLauncher").join("Data").join("Manifests");
    let entries = match fs::read_dir(&manifests_dir) { Ok(e) => e, Err(_) => return result };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().map(|e| e != "item").unwrap_or(true) { continue; }
        let content = match fs::read_to_string(&path) { Ok(c) => c, Err(_) => continue };
        let json: serde_json::Value = match serde_json::from_str(&content) { Ok(j) => j, Err(_) => continue };
        let name = json.get("DisplayName").and_then(|v| v.as_str());
        let install_loc = json.get("InstallLocation").and_then(|v| v.as_str());
        let exe_rel = json.get("LaunchExecutable").and_then(|v| v.as_str());
        if let (Some(name), Some(install_loc), Some(exe_rel)) = (name, install_loc, exe_rel) {
            let full = Path::new(install_loc).join(exe_rel);
            if full.exists() {
                result.push(InstalledGame {
                    name: name.to_string(),
                    exe_path: full.to_string_lossy().to_string(),
                    source: "epic".to_string(),
                });
            }
        }
    }
    result
}

#[cfg(not(target_os = "windows"))]
fn scan_steam_games() -> Vec<InstalledGame> { Vec::new() }
#[cfg(not(target_os = "windows"))]
fn scan_epic_games() -> Vec<InstalledGame> { Vec::new() }
#[cfg(not(target_os = "windows"))]
fn scan_ubisoft_games() -> Vec<InstalledGame> { Vec::new() }
#[cfg(not(target_os = "windows"))]
fn scan_rockstar_games() -> Vec<InstalledGame> { Vec::new() }

#[derive(Serialize)]
struct ProcessMemInfo {
    name: String,
    memory_mb: f64,
}

#[derive(Serialize)]
struct RamDetails {
    total_gb: f64,
    used_gb: f64,
    free_mb: f64,
    cached_mb: f64,
    pressure_percent: f64,
    top_processes: Vec<ProcessMemInfo>,
}

/// Dados detalhados de memória pra aba RAM: total/uso/livre/cache reais,
/// e os processos que mais consomem RAM agora — pra mostrar exatamente
/// o que está pesando, não só um número solto.
#[tauri::command]
async fn get_ram_details(state: State<'_, SysState>) -> Result<RamDetails, String> {
    let (total, used, free, top_processes) = {
        let mut sys = state.0.lock().unwrap();
        sys.refresh_memory();
        sys.refresh_processes(ProcessesToUpdate::All, true);

        let total = sys.total_memory() as f64;
        let used = sys.used_memory() as f64;
        let free = sys.free_memory() as f64;

        let mut processes: Vec<ProcessMemInfo> = sys
            .processes()
            .values()
            .map(|p| ProcessMemInfo {
                name: p.name().to_string_lossy().to_string(),
                memory_mb: p.memory() as f64 / 1_048_576.0,
            })
            .filter(|p| p.memory_mb > 30.0) // ignora processos irrelevantes
            .collect();

        // soma processos com o mesmo nome (ex: várias abas/instâncias do mesmo app)
        let mut grouped: std::collections::HashMap<String, f64> = std::collections::HashMap::new();
        for p in processes.drain(..) {
            *grouped.entry(p.name).or_insert(0.0) += p.memory_mb;
        }
        let mut top_processes: Vec<ProcessMemInfo> = grouped
            .into_iter()
            .map(|(name, memory_mb)| ProcessMemInfo {
                name,
                memory_mb: (memory_mb * 10.0).round() / 10.0,
            })
            .collect();
        top_processes.sort_by(|a, b| b.memory_mb.partial_cmp(&a.memory_mb).unwrap());
        top_processes.truncate(8);

        (total, used, free, top_processes)
    };

    // Lê o contador real "Cache Bytes" do Windows (o mesmo que o Gerenciador de
    // Tarefas usa) em vez de estimar — assim o número realmente reflete o que
    // a limpeza afeta, e cai de verdade quando você limpa.
    let cached = tauri::async_runtime::spawn_blocking(read_cache_bytes_windows)
        .await
        .unwrap_or(0.0);

    Ok(RamDetails {
        total_gb: (total / 1_073_741_824.0 * 10.0).round() / 10.0,
        used_gb: (used / 1_073_741_824.0 * 10.0).round() / 10.0,
        free_mb: (free / 1_048_576.0 * 10.0).round() / 10.0,
        cached_mb: (cached / 1_048_576.0 * 10.0).round() / 10.0,
        pressure_percent: if total > 0.0 { (used / total * 100.0 * 10.0).round() / 10.0 } else { 0.0 },
        top_processes,
    })
}

#[derive(Serialize)]
struct SystemStats {
    cpu_percent: f64,
    ram_used_gb: f64,
    ram_total_gb: f64,
    ram_percent: f64,
    gpu_percent: Option<f64>,
    disks: Vec<DiskInfo>,
}

/// Lê o uso real de CPU e RAM via sysinfo (biblioteca nativa, sem depender
/// de comandos externos — bem rápido, roda em memória). A checagem de GPU
/// é opcional (include_gpu) porque ela precisa abrir um processo do
/// PowerShell nos bastidores e é bem mais lenta — por isso só é chamada
/// de vez em quando pelo frontend, nunca a cada atualização.
#[tauri::command]
async fn get_system_stats(state: State<'_, SysState>, include_gpu: bool) -> Result<SystemStats, String> {
    let (cpu_percent, ram_used_gb, ram_total_gb, ram_percent) = {
        let mut sys = state.0.lock().unwrap();
        sys.refresh_cpu_usage();
        sys.refresh_memory();

        let cpu = sys.global_cpu_usage() as f64;
        let total = sys.total_memory() as f64 / 1_073_741_824.0;
        let used = sys.used_memory() as f64 / 1_073_741_824.0;
        let percent = if total > 0.0 { (used / total) * 100.0 } else { 0.0 };
        (cpu, used, total, percent)
    };

    let disks_list = Disks::new_with_refreshed_list();
    let disks: Vec<DiskInfo> = disks_list
        .iter()
        .map(|d| {
            let total = d.total_space() as f64 / 1_073_741_824.0;
            let avail = d.available_space() as f64 / 1_073_741_824.0;
            let used = (total - avail).max(0.0);
            let percent = if total > 0.0 { (used / total) * 100.0 } else { 0.0 };
            DiskInfo {
                name: d.mount_point().to_string_lossy().to_string(),
                used_gb: (used * 10.0).round() / 10.0,
                total_gb: (total * 10.0).round() / 10.0,
                percent: (percent * 10.0).round() / 10.0,
                is_ssd: d.is_removable() == false && matches!(d.kind(), sysinfo::DiskKind::SSD),
            }
        })
        .collect();

    // GPU: sysinfo não lê uso de GPU. Usamos o contador nativo de performance
    // do Windows (GPU Engine), que funciona pra qualquer fabricante (NVIDIA/AMD/Intel)
    // sem precisar instalar nada extra — mas roda numa thread separada (spawn_blocking)
    // pra nunca travar a interface, e só quando o frontend realmente pede.
    let gpu_percent = if include_gpu {
        tauri::async_runtime::spawn_blocking(read_gpu_usage_windows)
            .await
            .unwrap_or(0.0)
    } else {
        return Ok(SystemStats {
            cpu_percent: (cpu_percent * 10.0).round() / 10.0,
            ram_used_gb: (ram_used_gb * 10.0).round() / 10.0,
            ram_total_gb: (ram_total_gb * 10.0).round() / 10.0,
            ram_percent: (ram_percent * 10.0).round() / 10.0,
            gpu_percent: None,
            disks,
        });
    };

    Ok(SystemStats {
        cpu_percent: (cpu_percent * 10.0).round() / 10.0,
        ram_used_gb: (ram_used_gb * 10.0).round() / 10.0,
        ram_total_gb: (ram_total_gb * 10.0).round() / 10.0,
        ram_percent: (ram_percent * 10.0).round() / 10.0,
        gpu_percent: Some(gpu_percent),
        disks,
    })
}

#[derive(Serialize)]
struct DiagnosticCheck {
    label: String,
    status: String, // "ok" | "warn" | "bad"
    detail: String,
}

#[derive(Serialize)]
struct DiagnosticReport {
    checks: Vec<DiagnosticCheck>,
}

/// Roda uma checagem rápida e real da máquina (sem precisar de UAC, só leitura):
/// espaço em disco, saúde física dos discos (S.M.A.R.T.), dispositivos com erro
/// no Gerenciador de Dispositivos, e erros críticos recentes no Log de Eventos.
/// Não roda SFC/DISM aqui de propósito — isso demora minutos e travaria o clique.
#[tauri::command]
async fn run_diagnostics(state: State<'_, SysState>) -> Result<DiagnosticReport, String> {
    let (cpu_percent, ram_percent) = {
        let mut sys = state.0.lock().unwrap();
        sys.refresh_cpu_usage();
        sys.refresh_memory();
        let cpu = sys.global_cpu_usage() as f64;
        let total = sys.total_memory() as f64;
        let used = sys.used_memory() as f64;
        let ram = if total > 0.0 { (used / total) * 100.0 } else { 0.0 };
        (cpu, ram)
    };

    let mut checks = Vec::new();

    // Espaço livre em disco (sysinfo, funciona em qualquer SO)
    let disks_list = Disks::new_with_refreshed_list();
    let mut low_space: Vec<String> = Vec::new();
    for d in disks_list.iter() {
        let total = d.total_space() as f64;
        let avail = d.available_space() as f64;
        if total <= 0.0 { continue; }
        let free_pct = (avail / total) * 100.0;
        if free_pct < 10.0 {
            let name = d.mount_point().to_string_lossy().to_string();
            low_space.push(format!("{name} ({:.0}% livre)", free_pct));
        }
    }
    checks.push(if low_space.is_empty() {
        DiagnosticCheck{ label: "Espaço em disco".into(), status: "ok".into(), detail: "Espaço livre saudável em todos os discos".into() }
    } else {
        DiagnosticCheck{ label: "Espaço em disco".into(), status: "warn".into(), detail: format!("Pouco espaço livre: {}", low_space.join(", ")) }
    });

    // Uso atual de CPU/RAM
    checks.push(if cpu_percent >= 90.0 {
        DiagnosticCheck{ label: "Uso de CPU".into(), status: "bad".into(), detail: format!("CPU em {:.0}% agora — algo pode estar travando o sistema", cpu_percent) }
    } else if cpu_percent >= 75.0 {
        DiagnosticCheck{ label: "Uso de CPU".into(), status: "warn".into(), detail: format!("CPU em {:.0}% agora", cpu_percent) }
    } else {
        DiagnosticCheck{ label: "Uso de CPU".into(), status: "ok".into(), detail: format!("CPU em {:.0}%, dentro do normal", cpu_percent) }
    });
    checks.push(if ram_percent >= 90.0 {
        DiagnosticCheck{ label: "Uso de RAM".into(), status: "bad".into(), detail: format!("RAM em {:.0}% agora — considere fechar programas", ram_percent) }
    } else if ram_percent >= 80.0 {
        DiagnosticCheck{ label: "Uso de RAM".into(), status: "warn".into(), detail: format!("RAM em {:.0}% agora", ram_percent) }
    } else {
        DiagnosticCheck{ label: "Uso de RAM".into(), status: "ok".into(), detail: format!("RAM em {:.0}%, dentro do normal", ram_percent) }
    });

    // Checagens específicas do Windows (dispositivos, saúde física dos discos, eventos)
    let (dev_status, dev_detail) = check_device_errors_windows();
    checks.push(DiagnosticCheck{ label: "Dispositivos (drivers)".into(), status: dev_status, detail: dev_detail });

    let (disk_status, disk_detail) = check_disk_health_windows();
    checks.push(DiagnosticCheck{ label: "Saúde física dos discos".into(), status: disk_status, detail: disk_detail });

    let (evt_status, evt_detail) = check_recent_critical_events_windows();
    checks.push(DiagnosticCheck{ label: "Erros críticos recentes".into(), status: evt_status, detail: evt_detail });

    Ok(DiagnosticReport{ checks })
}

/// Analisa um jogo específico (pelo caminho do .exe): confere se os ajustes de
/// performance já foram aplicados pra ele, se tem espaço livre suficiente no disco
/// onde ele está instalado, o uso atual de CPU/RAM da máquina, e lista os apps mais
/// pesados rodando agora que podem estar competindo por recurso.
/// Não estima "tantos % de FPS a mais" — isso exigiria rodar o jogo com benchmark
/// de verdade, o que este app não faz. O que dá pra afirmar com dado real é isto aqui.
#[tauri::command]
async fn analyze_game(state: State<'_, SysState>, exe_path: String) -> Result<DiagnosticReport, String> {
    let mut checks = Vec::new();
    let exe_name = exe_path.split(['\\', '/']).last().unwrap_or(&exe_path).to_string();

    let (cpu_percent, ram_percent, running, heavy_procs) = {
        let mut sys = state.0.lock().unwrap();
        sys.refresh_cpu_usage();
        sys.refresh_memory();
        sys.refresh_processes(ProcessesToUpdate::All, true);
        let cpu = sys.global_cpu_usage() as f64;
        let total = sys.total_memory() as f64;
        let used = sys.used_memory() as f64;
        let ram = if total > 0.0 { (used / total) * 100.0 } else { 0.0 };

        let running = sys.processes().values().any(|p| {
            p.name().to_string_lossy().eq_ignore_ascii_case(&exe_name)
        });

        // apps pesados (>400MB) rodando agora, exceto o próprio jogo e processos do sistema/app
        let ignore_names = ["fluxtweakers", "system", "registry", "memory compression", &exe_name.to_lowercase()];
        let mut grouped: std::collections::HashMap<String, f64> = std::collections::HashMap::new();
        for p in sys.processes().values() {
            let name = p.name().to_string_lossy().to_string();
            if ignore_names.iter().any(|i| name.to_lowercase().contains(i)) { continue; }
            *grouped.entry(name).or_insert(0.0) += p.memory() as f64 / 1_048_576.0;
        }
        let mut heavy: Vec<(String, f64)> = grouped.into_iter().filter(|(_, mb)| *mb > 400.0).collect();
        heavy.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        heavy.truncate(3);
        (cpu, ram, running, heavy)
    };

    checks.push(DiagnosticCheck{
        label: "Status agora".into(),
        status: "ok".into(),
        detail: if running { format!("{exe_name} está rodando neste momento") } else { format!("{exe_name} não está aberto agora — os números de CPU/RAM abaixo são da máquina em geral, não do jogo") },
    });

    // espaço livre no disco onde o jogo está instalado
    let drive_prefix: String = exe_path.chars().take(3).collect();
    let disks_list = Disks::new_with_refreshed_list();
    if let Some(disk) = disks_list.iter().find(|d| {
        d.mount_point().to_string_lossy().to_uppercase().starts_with(&drive_prefix.to_uppercase())
    }) {
        let total = disk.total_space() as f64;
        let avail = disk.available_space() as f64;
        let free_gb = avail / 1_073_741_824.0;
        let free_pct = if total > 0.0 { (avail / total) * 100.0 } else { 0.0 };
        checks.push(if free_pct < 8.0 {
            DiagnosticCheck{ label: "Espaço em disco".into(), status: "bad".into(), detail: format!("Só {:.0} GB livres no disco do jogo ({:.0}%) — isso pode causar engasgos de streaming de textura", free_gb, free_pct) }
        } else if free_pct < 15.0 {
            DiagnosticCheck{ label: "Espaço em disco".into(), status: "warn".into(), detail: format!("{:.0} GB livres no disco do jogo ({:.0}%) — vale liberar espaço", free_gb, free_pct) }
        } else {
            DiagnosticCheck{ label: "Espaço em disco".into(), status: "ok".into(), detail: format!("{:.0} GB livres no disco do jogo", free_gb) }
        });
    }

    // tweaks de performance já aplicados pra esse exe especificamente
    let (cpu_pri_status, cpu_pri_detail) = check_game_cpu_priority_windows(&exe_name);
    checks.push(DiagnosticCheck{ label: "Prioridade de CPU".into(), status: cpu_pri_status, detail: cpu_pri_detail });

    let (gpu_pref_status, gpu_pref_detail) = check_game_gpu_preference_windows(&exe_path);
    checks.push(DiagnosticCheck{ label: "Preferência de GPU".into(), status: gpu_pref_status, detail: gpu_pref_detail });

    let (fso_status, fso_detail) = check_game_fso_windows(&exe_path);
    checks.push(DiagnosticCheck{ label: "Otimizações de tela cheia".into(), status: fso_status, detail: fso_detail });

    // uso atual de CPU/RAM da máquina
    checks.push(if cpu_percent >= 85.0 {
        DiagnosticCheck{ label: "CPU disponível agora".into(), status: "warn".into(), detail: format!("CPU já em {:.0}% de uso — pouca folga sobrando pro jogo", cpu_percent) }
    } else {
        DiagnosticCheck{ label: "CPU disponível agora".into(), status: "ok".into(), detail: format!("CPU em {:.0}%, com folga", cpu_percent) }
    });
    checks.push(if ram_percent >= 85.0 {
        DiagnosticCheck{ label: "RAM disponível agora".into(), status: "warn".into(), detail: format!("RAM já em {:.0}% de uso — pode faltar memória durante o jogo", ram_percent) }
    } else {
        DiagnosticCheck{ label: "RAM disponível agora".into(), status: "ok".into(), detail: format!("RAM em {:.0}%, com folga", ram_percent) }
    });

    if !heavy_procs.is_empty() {
        let list = heavy_procs.iter().map(|(n, mb)| format!("{n} ({:.0} MB)", mb)).collect::<Vec<_>>().join(", ");
        checks.push(DiagnosticCheck{ label: "Apps pesados rodando agora".into(), status: "warn".into(), detail: format!("{list} — feche o que não precisar antes de jogar") });
    } else {
        checks.push(DiagnosticCheck{ label: "Apps pesados rodando agora".into(), status: "ok".into(), detail: "Nada consumindo memória pesado em segundo plano".into() });
    }

    Ok(DiagnosticReport{ checks })
}

#[cfg(target_os = "windows")]
fn check_game_cpu_priority_windows(exe_name: &str) -> (String, String) {
    let key = format!(r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\{exe_name}\PerfOptions");
    match reg_query_value(&key, "CpuPriorityClass") {
        Some(v) if v.trim() == "0x3" => ("ok".to_string(), "Prioridade Alta já configurada pra esse jogo".to_string()),
        _ => ("warn".to_string(), "Prioridade padrão (Normal) — use o preset Desempenho na aba Meus Jogos pra subir".to_string()),
    }
}
#[cfg(target_os = "windows")]
fn check_game_gpu_preference_windows(exe_path: &str) -> (String, String) {
    match reg_query_value(r"HKCU\Software\Microsoft\DirectX\UserGpuPreference", exe_path) {
        Some(v) if v.contains("GpuPreference=2") => ("ok".to_string(), "Já configurado pra usar a GPU dedicada/de alto desempenho".to_string()),
        _ => ("warn".to_string(), "Ainda no automático — use o preset Desempenho na aba Meus Jogos pra forçar a GPU dedicada".to_string()),
    }
}
#[cfg(target_os = "windows")]
fn check_game_fso_windows(exe_path: &str) -> (String, String) {
    let key = r"HKCU\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers";
    match reg_query_value(key, exe_path) {
        Some(v) if v.contains("DISABLEDXMAXIMIZEDWINDOWEDMODE") => ("ok".to_string(), "Otimizações de tela cheia já desativadas (reduz latência)".to_string()),
        _ => ("warn".to_string(), "Otimizações de tela cheia do Windows ainda ativas — o preset Desempenho desativa isso".to_string()),
    }
}
#[cfg(not(target_os = "windows"))]
fn check_game_cpu_priority_windows(_exe_name: &str) -> (String, String) { ("ok".to_string(), "Checagem disponível apenas no Windows".to_string()) }
#[cfg(not(target_os = "windows"))]
fn check_game_gpu_preference_windows(_exe_path: &str) -> (String, String) { ("ok".to_string(), "Checagem disponível apenas no Windows".to_string()) }
#[cfg(not(target_os = "windows"))]
fn check_game_fso_windows(_exe_path: &str) -> (String, String) { ("ok".to_string(), "Checagem disponível apenas no Windows".to_string()) }

#[cfg(target_os = "windows")]
fn check_device_errors_windows() -> (String, String) {
    let ps_cmd = "(Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue | Where-Object { $_.ConfigManagerErrorCode -ne 0 }).FriendlyName -join ', '";
    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if text.is_empty() {
                ("ok".to_string(), "Nenhum dispositivo com erro de driver".to_string())
            } else {
                ("bad".to_string(), format!("Dispositivos com erro: {text}"))
            }
        }
        Err(_) => ("warn".to_string(), "Não foi possível checar (permissão ou PowerShell indisponível)".to_string()),
    }
}

#[cfg(target_os = "windows")]
fn check_disk_health_windows() -> (String, String) {
    let ps_cmd = "(Get-PhysicalDisk -ErrorAction SilentlyContinue | Where-Object { $_.HealthStatus -ne 'Healthy' }).FriendlyName -join ', '";
    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if text.is_empty() {
                ("ok".to_string(), "Todos os discos reportam saúde OK (S.M.A.R.T.)".to_string())
            } else {
                ("bad".to_string(), format!("Discos com alerta de saúde: {text}"))
            }
        }
        Err(_) => ("warn".to_string(), "Não foi possível checar a saúde dos discos".to_string()),
    }
}

#[cfg(target_os = "windows")]
fn check_recent_critical_events_windows() -> (String, String) {
    let ps_cmd = "(Get-WinEvent -FilterHashtable @{LogName='System'; Level=1,2; StartTime=(Get-Date).AddHours(-24)} -ErrorAction SilentlyContinue | Measure-Object).Count";
    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout).trim().to_string();
            let count: i64 = text.parse().unwrap_or(0);
            if count == 0 {
                ("ok".to_string(), "Nenhum erro crítico nas últimas 24h".to_string())
            } else if count <= 5 {
                ("warn".to_string(), format!("{count} erro(s) crítico(s) nas últimas 24h"))
            } else {
                ("bad".to_string(), format!("{count} erros críticos nas últimas 24h — vale investigar"))
            }
        }
        Err(_) => ("warn".to_string(), "Não foi possível checar o Log de Eventos".to_string()),
    }
}

#[cfg(not(target_os = "windows"))]
fn check_device_errors_windows() -> (String, String) {
    ("ok".to_string(), "Checagem disponível apenas no Windows".to_string())
}
#[cfg(not(target_os = "windows"))]
fn check_disk_health_windows() -> (String, String) {
    ("ok".to_string(), "Checagem disponível apenas no Windows".to_string())
}
#[cfg(not(target_os = "windows"))]
fn check_recent_critical_events_windows() -> (String, String) {
    ("ok".to_string(), "Checagem disponível apenas no Windows".to_string())
}

#[cfg(target_os = "windows")]
fn read_gpu_usage_windows() -> f64 {
    // Soma a utilização de todos os "engines" do tipo 3D de todas as GPUs —
    // é o mesmo contador que o Gerenciador de Tarefas do Windows usa.
    let ps_cmd = "(Get-Counter '\\GPU Engine(*engtype_3D)\\Utilization Percentage' -ErrorAction SilentlyContinue).CounterSamples | Measure-Object -Property CookedValue -Sum | Select-Object -ExpandProperty Sum";

    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();

    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout);
            let val: f64 = text.trim().replace(',', ".").parse().unwrap_or(0.0);
            val.min(100.0).max(0.0)
        }
        Err(_) => 0.0,
    }
}

#[cfg(not(target_os = "windows"))]
fn read_gpu_usage_windows() -> f64 {
    0.0
}

#[cfg(target_os = "windows")]
fn read_cache_bytes_windows() -> f64 {
    // Mesmo contador que o Gerenciador de Tarefas usa pra mostrar "Em cache" —
    // é isso que realmente cai quando a limpeza de Standby List roda de verdade.
    let ps_cmd = "(Get-Counter '\\Memory\\Cache Bytes' -ErrorAction SilentlyContinue).CounterSamples[0].CookedValue";

    let output = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", ps_cmd])
        .creation_flags(CREATE_NO_WINDOW)
        .output();

    match output {
        Ok(o) => {
            let text = String::from_utf8_lossy(&o.stdout);
            text.trim().replace(',', ".").parse().unwrap_or(0.0)
        }
        Err(_) => 0.0,
    }
}

#[cfg(not(target_os = "windows"))]
fn read_cache_bytes_windows() -> f64 {
    0.0
}

#[derive(Serialize)]
struct DeepScanResult {
    status: String,  // "ok" | "fixed" | "unfixable" | "error"
    summary: String,
    raw_tail: String,
}

/// Roda sfc /scannow + DISM /ScanHealth de verdade, elevado (pede UAC), e espera
/// terminar pra ler o resultado real de um arquivo temporário — diferente do
/// run_bat_script (que é fire-and-forget), aqui a gente PRECISA do resultado.
/// Isso demora vários minutos de propósito (é o Windows verificando arquivo por
/// arquivo do sistema), então só deve ser chamado quando o usuário pedir
/// explicitamente uma verificação profunda, não no "Analisar Sistema" rápido.
#[cfg(target_os = "windows")]
#[tauri::command]
async fn run_deep_scan() -> Result<DeepScanResult, String> {
    let temp_dir = std::env::temp_dir();
    let out_path = temp_dir.join(format!("dgeras-scan-{}.log", uuid_like()));
    let bat_path = temp_dir.join(format!("dgeras-scan-{}.bat", uuid_like()));

    let script = format!(
        "@echo off\r\nchcp 65001 >nul\r\necho ===SFC=== > \"{out}\"\r\nsfc /scannow >> \"{out}\" 2>&1\r\necho ===DISM=== >> \"{out}\"\r\nDISM /Online /Cleanup-Image /ScanHealth >> \"{out}\" 2>&1\r\necho ===FIM===>> \"{out}\"\r\n",
        out = out_path.to_string_lossy()
    );
    fs::write(&bat_path, script).map_err(|e| format!("Falha ao preparar a verificação: {e}"))?;

    let ps_launcher = format!(
        "$p = Start-Process -FilePath 'cmd.exe' -ArgumentList '/c \"{path}\"' -Verb RunAs -WindowStyle Hidden -Wait -PassThru; exit $p.ExitCode",
        path = bat_path.to_string_lossy().replace('\'', "''")
    );

    // sfc/DISM podem levar minutos — isso BLOQUEIA a thread até terminar, então roda
    // numa thread dedicada (spawn_blocking) pra não travar o runtime assíncrono do
    // Tauri, que é o mesmo canal usado pra entregar a resposta de volta pro app.
    // Sem isso, o app fica preso em "Verificando..." pra sempre mesmo quando o
    // Windows já terminou (a resposta nunca consegue "voltar" pra tela).
    let ps_launcher_owned = ps_launcher.clone();
    let output = tokio::task::spawn_blocking(move || {
        Command::new("powershell")
            .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher_owned])
            .creation_flags(CREATE_NO_WINDOW)
            .output()
    })
    .await
    .map_err(|e| format!("Falha interna ao rodar a verificação: {e}"))?;

    let _ = fs::remove_file(&bat_path);

    match output {
        Ok(out) => {
            let content = fs::read_to_string(&out_path).unwrap_or_default();
            let _ = fs::remove_file(&out_path);
            if content.trim().is_empty() {
                // código 1223 = "operação cancelada pelo usuário" (UAC negado/fechado)
                let stderr = String::from_utf8_lossy(&out.stderr);
                let cancelled = out.status.code() == Some(1223) || stderr.contains("1223") || stderr.to_lowercase().contains("cancel");
                let msg = if cancelled {
                    "A janela de permissão de administrador (UAC) foi cancelada ou fechada, então a verificação não rodou. Clique em 'Rodar verificação profissional' de novo e aceite a permissão."
                } else {
                    "Não consegui ler o resultado da verificação. Pode tentar de novo — se continuar assim, algum antivírus pode estar bloqueando."
                };
                return Ok(DeepScanResult{ status: "error".into(), summary: msg.into(), raw_tail: stderr.trim().to_string() });
            }
            Ok(parse_sfc_result(&content))
        }
        Err(e) => Err(format!("Falha ao rodar a verificação: {e}")),
    }
}

#[cfg(target_os = "windows")]
fn parse_sfc_result(content: &str) -> DeepScanResult {
    let lower = content.to_lowercase();
    let (status, summary) = if lower.contains("não encontrou nenhuma violação") || lower.contains("did not find any integrity violations") {
        ("ok", "Nenhum arquivo de sistema corrompido encontrado. Tudo íntegro.")
    } else if lower.contains("encontrou arquivos corrompidos e") && (lower.contains("reparou") || lower.contains("êxito")) || lower.contains("successfully repaired") {
        ("fixed", "Encontrou arquivos de sistema corrompidos e conseguiu reparar todos automaticamente.")
    } else if lower.contains("não foi possível corrigir") || lower.contains("unable to fix") {
        ("unfixable", "Encontrou arquivos corrompidos mas não conseguiu corrigir todos — pode indicar um problema mais sério no disco ou instalação do Windows.")
    } else if lower.contains("não pôde executar") || lower.contains("could not perform") {
        ("error", "O Windows não conseguiu completar a verificação (geralmente precisa rodar em Modo de Segurança ou verificar o disco antes).")
    } else {
        ("error", "Verificação concluída, mas não consegui interpretar automaticamente o resultado — veja o texto bruto abaixo.")
    };
    // guarda as últimas linhas não-vazias como evidência bruta, sem exagerar no tamanho
    let tail: Vec<&str> = content.lines().filter(|l| !l.trim().is_empty()).collect();
    let raw_tail = tail.iter().rev().take(12).rev().cloned().collect::<Vec<_>>().join("\n");
    DeepScanResult{ status: status.to_string(), summary: summary.to_string(), raw_tail }
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
async fn run_deep_scan() -> Result<DeepScanResult, String> {
    Ok(DeepScanResult{ status: "error".into(), summary: "Disponível só no Windows".into(), raw_tail: String::new() })
}

/// Recebe o texto do .bat gerado pelo painel, salva num arquivo temporário
/// e executa TOTALMENTE ESCONDIDO (sem console piscando, sem downloads).
/// O único aviso que aparece pro usuário é o próprio UAC do Windows pedindo
/// permissão de administrador — isso o sistema operacional exige e não dá
/// pra pular, mas fora isso roda tudo em segundo plano dentro do app.
#[tauri::command]
fn run_bat_script(script_text: String) -> Result<String, String> {
    let temp_dir = std::env::temp_dir();
    let file_name = format!("dgeras-run-{}.bat", uuid_like());
    let file_path = temp_dir.join(&file_name);

    fs::write(&file_path, script_text).map_err(|e| format!("Falha ao gravar script: {e}"))?;

    let path_str = file_path.to_string_lossy().to_string();

    // Usa o PowerShell só como "lançador" elevado: Start-Process com -Verb RunAs
    // dispara o UAC, e -WindowStyle Hidden garante que nenhuma janela de console
    // apareça enquanto o .bat roda por trás. -Wait espera o script terminar.
    let ps_launcher = format!(
        "Start-Process -FilePath 'cmd.exe' -ArgumentList '/c \"{path}\"' -Verb RunAs -WindowStyle Hidden -Wait",
        path = path_str.replace('\'', "''")
    );

    #[cfg(target_os = "windows")]
    let result = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn();

    #[cfg(not(target_os = "windows"))]
    let result = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .spawn();

    match result {
        Ok(_) => Ok("Ajustes aplicados com sucesso".to_string()),
        Err(e) => Err(format!("Falha ao executar script: {e}")),
    }
}

fn uuid_like() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{nanos:x}")
}

// ===== Limpeza de RAM (mesma técnica do ISLC / RAMMap) =====
//
// O Windows guarda na "Standby List" partes de memória que já foram usadas
// mas não estão mais ativas — ele mantém isso em cache achando que você pode
// precisar de novo, só que às vezes isso deixa a RAM "presa" sem uso real.
// A limpeza chama a mesma função interna do Windows (NtSetSystemInformation)
// que o Gerenciador de Tarefas e ferramentas como RAMMap usam.
//
// Isso PRECISA de admin. Pra não pedir senha toda hora (o objetivo é rodar
// sozinho a cada 3 minutos), a gente cria uma Tarefa Agendada do Windows UMA
// VEZ (pede UAC só nessa primeira vez), configurada como "privilégios mais
// altos". Depois disso, o app só manda essa tarefa "rodar agora"
// (schtasks /run), o que não pede senha de novo — o Windows já confia na
// tarefa desde que ela foi criada com privilégio elevado.

const RAM_CLEAN_TASK_NAME: &str = "FluxTweakersRamClean";

fn ram_clean_ps1_content() -> &'static str {
    r#"
$sig = @"
using System;
using System.Runtime.InteropServices;
public class FluxRam {
    [DllImport("ntdll.dll")]
    public static extern int NtSetSystemInformation(int InfoClass, IntPtr Info, int Length);

    [DllImport("advapi32.dll", SetLastError = true)]
    public static extern bool OpenProcessToken(IntPtr ProcessHandle, uint DesiredAccess, out IntPtr TokenHandle);

    [DllImport("advapi32.dll", SetLastError = true)]
    public static extern bool LookupPrivilegeValue(string lpSystemName, string lpName, out long lpLuid);

    [StructLayout(LayoutKind.Sequential)]
    public struct LUID_AND_ATTRIBUTES { public long Luid; public uint Attributes; }

    [StructLayout(LayoutKind.Sequential)]
    public struct TOKEN_PRIVILEGES { public uint PrivilegeCount; public LUID_AND_ATTRIBUTES Privileges; }

    [DllImport("advapi32.dll", SetLastError = true)]
    public static extern bool AdjustTokenPrivileges(IntPtr TokenHandle, bool DisableAllPrivileges,
        ref TOKEN_PRIVILEGES NewState, uint BufferLength, IntPtr PreviousState, IntPtr ReturnLength);

    [DllImport("kernel32.dll")]
    public static extern IntPtr GetCurrentProcess();

    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern IntPtr OpenProcess(uint processAccess, bool bInheritHandle, int processId);

    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool CloseHandle(IntPtr hObject);

    [DllImport("psapi.dll", SetLastError = true)]
    public static extern bool EmptyWorkingSet(IntPtr hProcess);
}
"@
Add-Type -TypeDefinition $sig -ErrorAction SilentlyContinue

$before = (Get-Counter '\Memory\Available MBytes').CounterSamples[0].CookedValue

function Enable-Priv($name) {
    $TOKEN_ADJUST_PRIVILEGES = 0x20
    $TOKEN_QUERY = 0x8
    $hToken = [IntPtr]::Zero
    [FluxRam]::OpenProcessToken([FluxRam]::GetCurrentProcess(), ($TOKEN_ADJUST_PRIVILEGES -bor $TOKEN_QUERY), [ref]$hToken) | Out-Null
    $luid = 0
    [FluxRam]::LookupPrivilegeValue($null, $name, [ref]$luid) | Out-Null
    $priv = New-Object FluxRam+TOKEN_PRIVILEGES
    $priv.PrivilegeCount = 1
    $priv.Privileges = New-Object FluxRam+LUID_AND_ATTRIBUTES
    $priv.Privileges.Luid = $luid
    $priv.Privileges.Attributes = 0x2  # SE_PRIVILEGE_ENABLED
    [FluxRam]::AdjustTokenPrivileges($hToken, $false, [ref]$priv, 0, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null
}

# Habilita os dois privilégios que a limpeza de verdade precisa:
# - SeProfileSingleProcessPrivilege: pra purgar a standby list
# - SeDebugPrivilege: pra conseguir "tocar" em processos de outros usuários/sistema
#   e forçar eles a soltarem memória que não estão usando de verdade agora
Enable-Priv "SeProfileSingleProcessPrivilege"
Enable-Priv "SeDebugPrivilege"

$modeFile = "$env:TEMP\FluxTweakers\ram_action_mode.txt"
$mode = if (Test-Path $modeFile) { (Get-Content $modeFile -Raw).Trim() } else { "standby" }

if ($mode -eq "workingset") {
    # Técnica real de redução agressiva de RAM (mesma do Mem Reduct/RAMMap):
    # força cada processo a devolver pro Windows a memória "working set" que
    # não está sendo usada ativamente agora — é isso que derruba o número
    # de "em uso" de verdade, não só o cache.
    $PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
    $PROCESS_SET_QUOTA = 0x0100
    $access = $PROCESS_QUERY_LIMITED_INFORMATION -bor $PROCESS_SET_QUOTA

    Get-Process | ForEach-Object {
        try {
            $h = [FluxRam]::OpenProcess($access, $false, $_.Id)
            if ($h -ne [IntPtr]::Zero) {
                [FluxRam]::EmptyWorkingSet($h) | Out-Null
                [FluxRam]::CloseHandle($h) | Out-Null
            }
        } catch {}
    }
}

# Sempre purga a standby list também (cache "solto" que o Windows guarda),
# combinando os dois efeitos pro resultado mais completo possível.
$SystemMemoryListInformation = 80
$MemoryPurgeStandbyList = 4
$ptr = [System.Runtime.InteropServices.Marshal]::AllocHGlobal(4)
[System.Runtime.InteropServices.Marshal]::WriteInt32($ptr, $MemoryPurgeStandbyList)
$status = [FluxRam]::NtSetSystemInformation($SystemMemoryListInformation, $ptr, 4)
[System.Runtime.InteropServices.Marshal]::FreeHGlobal($ptr)

Start-Sleep -Milliseconds 500
$after = (Get-Counter '\Memory\Available MBytes').CounterSamples[0].CookedValue
$freed = [math]::Round($after - $before, 0)

$resultDir = "$env:TEMP\FluxTweakers"
New-Item -ItemType Directory -Force -Path $resultDir | Out-Null
if ($status -eq 0) {
    "OK|$freed" | Out-File -FilePath "$resultDir\ram_clean_result.txt" -Encoding utf8
} else {
    "ERRO|status=$status" | Out-File -FilePath "$resultDir\ram_clean_result.txt" -Encoding utf8
}
"#
}

/// Prepara tudo pra limpeza automática funcionar: grava o script de limpeza
/// num local fixo e registra a Tarefa Agendada elevada. Só precisa rodar
/// uma vez (pede UAC essa única vez); chamadas seguintes são silenciosas.
#[tauri::command]
fn setup_ram_cleaner() -> Result<String, String> {
    let dir = std::env::temp_dir().join("FluxTweakers");
    fs::create_dir_all(&dir).map_err(|e| format!("Falha ao criar pasta: {e}"))?;
    let ps1_path = dir.join("ram_clean.ps1");
    fs::write(&ps1_path, ram_clean_ps1_content())
        .map_err(|e| format!("Falha ao gravar script de limpeza: {e}"))?;

    let ps1_str = ps1_path.to_string_lossy().to_string();

    // Cria (ou substitui) a tarefa agendada, rodando como o usuário atual
    // com privilégios mais altos. O /SC ONCE /ST 00:00 é só um gatilho
    // "dummy" — na prática a gente sempre dispara manualmente via /run.
    let create_cmd = format!(
        "schtasks /Create /TN \"{name}\" /TR \"powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \\\"{script}\\\"\" /SC ONCE /ST 00:00 /RL HIGHEST /F",
        name = RAM_CLEAN_TASK_NAME,
        script = ps1_str
    );

    let ps_launcher = format!(
        "Start-Process -FilePath 'cmd.exe' -ArgumentList '/c {cmd}' -Verb RunAs -WindowStyle Hidden -Wait",
        cmd = create_cmd.replace('\'', "''")
    );

    #[cfg(target_os = "windows")]
    let result = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
        .and_then(|mut c| c.wait());

    #[cfg(not(target_os = "windows"))]
    let result: std::io::Result<std::process::ExitStatus> = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .spawn()
        .and_then(|mut c| c.wait());

    match result {
        Ok(_) => Ok("Limpeza automática de RAM configurada".to_string()),
        Err(e) => Err(format!("Falha ao configurar: {e}")),
    }
}

/// Dispara a limpeza (roda a tarefa agendada já configurada). Não pede UAC
/// de novo — a tarefa já "nasceu" elevada. Espera um pouco e lê o resultado
/// real gravado pelo script (sucesso + quanto de RAM foi liberado, ou erro).
/// `mode`: "standby" (cache padrão) ou "modified" (páginas modificadas pendentes).
#[tauri::command]
async fn run_ram_clean(mode: Option<String>) -> Result<String, String> {
    let dir = std::env::temp_dir().join("FluxTweakers");
    let _ = fs::create_dir_all(&dir);
    let mode_str = mode.unwrap_or_else(|| "standby".to_string());
    let _ = fs::write(dir.join("ram_action_mode.txt"), &mode_str);

    let result_path = dir.join("ram_clean_result.txt");
    let _ = fs::remove_file(&result_path); // limpa resultado antigo antes de rodar de novo

    // Confere se a tarefa agendada já existe (isso NÃO precisa de admin, só consulta).
    // Se ainda não existir (primeira vez que qualquer botão de RAM é usado, sem
    // ter passado pelo interruptor antes), configura ela agora mesmo — só nesse
    // caso vai pedir UAC uma vez; nas próximas chamadas já está tudo pronto.
    #[cfg(target_os = "windows")]
    let task_exists = Command::new("schtasks")
        .args(["/Query", "/TN", RAM_CLEAN_TASK_NAME])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    #[cfg(not(target_os = "windows"))]
    let task_exists = Command::new("schtasks")
        .args(["/Query", "/TN", RAM_CLEAN_TASK_NAME])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    if !task_exists {
        setup_ram_cleaner()?;
    }

    #[cfg(target_os = "windows")]
    let spawn_result = Command::new("schtasks")
        .args(["/Run", "/TN", RAM_CLEAN_TASK_NAME])
        .creation_flags(CREATE_NO_WINDOW)
        .output();

    #[cfg(not(target_os = "windows"))]
    let spawn_result = Command::new("schtasks")
        .args(["/Run", "/TN", RAM_CLEAN_TASK_NAME])
        .output();

    match spawn_result {
        Ok(o) if !o.status.success() => {
            return Err(format!(
                "Não consegui iniciar a tarefa de limpeza. ({})",
                String::from_utf8_lossy(&o.stderr).trim()
            ));
        }
        Err(e) => return Err(format!("Falha ao rodar limpeza: {e}")),
        _ => {}
    }

    // Espera até 6 segundos pelo resultado (o script leva menos de 1s normalmente,
    // mas dá uma folga pra máquinas mais lentas ou o Agendador demorar a iniciar).
    for _ in 0..30 {
        tokio::time::sleep(std::time::Duration::from_millis(200)).await;
        if let Ok(content) = fs::read_to_string(&result_path) {
            let content = content.trim();
            if let Some(freed) = content.strip_prefix("OK|") {
                let freed_mb: i64 = freed.parse().unwrap_or(0);
                return Ok(if freed_mb > 0 {
                    format!("RAM limpa — cerca de {freed_mb} MB liberados")
                } else {
                    "RAM limpa (cache já estava baixo, pouco a liberar)".to_string()
                });
            } else if let Some(err) = content.strip_prefix("ERRO|") {
                return Err(format!("O Windows recusou a limpeza ({err})"));
            }
        }
    }

    Err("A limpeza não respondeu a tempo — tente de novo".to_string())
}

// ===== Bordas arredondadas nativas (estilo Windows 11) =====
// O truque de CSS (transparência + border-radius) é frágil no Windows e nem
// sempre funciona. O jeito confiável — que Discord, Spotify e outros apps
// usam — é pedir pro próprio Windows arredondar a janela de verdade, via
// uma chamada direta à API do sistema (dwmapi.dll), sem precisar de
// nenhuma biblioteca externa.
#[cfg(target_os = "windows")]
#[link(name = "dwmapi")]
extern "system" {
    fn DwmSetWindowAttribute(
        hwnd: isize,
        dwattribute: u32,
        pvattribute: *const i32,
        cbattribute: u32,
    ) -> i32;
}

#[cfg(target_os = "windows")]
fn apply_native_rounded_corners(hwnd_raw: isize) {
    const DWMWA_WINDOW_CORNER_PREFERENCE: u32 = 33;
    const DWMWCP_ROUND: i32 = 2; // cantos arredondados "normais" do Windows 11
    unsafe {
        DwmSetWindowAttribute(
            hwnd_raw,
            DWMWA_WINDOW_CORNER_PREFERENCE,
            &DWMWCP_ROUND as *const i32,
            std::mem::size_of::<i32>() as u32,
        );
    }
}

/// Guarda em memória se o app deve minimizar pra bandeja (em vez de fechar de
/// verdade) quando o usuário clica no X. Carregado do disco na inicialização.
struct CloseBehaviorState(Mutex<bool>);

fn config_file_path(app: &tauri::AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_config_dir().ok()?;
    let _ = fs::create_dir_all(&dir);
    Some(dir.join("settings.json"))
}

fn load_close_behavior(app: &tauri::AppHandle) -> bool {
    if let Some(path) = config_file_path(app) {
        if let Ok(content) = fs::read_to_string(&path) {
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                if let Some(v) = json.get("close_to_tray").and_then(|v| v.as_bool()) {
                    return v;
                }
            }
        }
    }
    false // padrão: fechar o X fecha o app de verdade, igual sempre foi — só muda se o usuário ligar
}

/// Diz se o app está configurado pra minimizar pra bandeja ao fechar (em vez de sair).
#[tauri::command]
fn get_close_behavior(state: State<CloseBehaviorState>) -> bool {
    *state.0.lock().unwrap()
}

/// Liga/desliga "minimizar pra bandeja ao fechar" e salva a escolha no disco,
/// pra lembrar na próxima vez que o app abrir.
#[tauri::command]
fn set_close_behavior(app: tauri::AppHandle, state: State<CloseBehaviorState>, enabled: bool) -> Result<(), String> {
    *state.0.lock().unwrap() = enabled;
    if let Some(path) = config_file_path(&app) {
        let json = serde_json::json!({ "close_to_tray": enabled });
        fs::write(&path, json.to_string()).map_err(|e| format!("Não consegui salvar a preferência: {e}"))?;
    }
    Ok(())
}

/// Diz se o FluxTweakers está configurado pra abrir sozinho quando o Windows inicia.
#[tauri::command]
fn get_autostart_enabled(app: tauri::AppHandle) -> Result<bool, String> {
    use tauri_plugin_autostart::ManagerExt;
    app.autolaunch().is_enabled().map_err(|e| format!("Não consegui checar: {e}"))
}

/// Liga/desliga o app abrir sozinho com o Windows (usa a tarefa de inicialização
/// oficial do Windows, o mesmo mecanismo que outros programas usam).
#[tauri::command]
fn set_autostart_enabled(app: tauri::AppHandle, enabled: bool) -> Result<(), String> {
    use tauri_plugin_autostart::ManagerExt;
    let mgr = app.autolaunch();
    if enabled {
        mgr.enable().map_err(|e| format!("Não consegui ativar: {e}"))
    } else {
        mgr.disable().map_err(|e| format!("Não consegui desativar: {e}"))
    }
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_autostart::init(tauri_plugin_autostart::MacosLauncher::LaunchAgent, None))
        .manage(SysState(Mutex::new(System::new_all())))
        .invoke_handler(tauri::generate_handler![run_bat_script, get_system_stats, setup_ram_cleaner, run_ram_clean, get_hardware_info, get_ram_details, run_diagnostics, scan_installed_games, analyze_game, apply_game_graphics_preset, run_deep_scan, get_close_behavior, set_close_behavior, get_autostart_enabled, set_autostart_enabled, list_power_plans])
        .setup(|app| {
            let close_to_tray = load_close_behavior(&app.handle());
            app.manage(CloseBehaviorState(Mutex::new(close_to_tray)));

            #[cfg(target_os = "windows")]
            {
                if let Some(window) = app.get_webview_window("main") {
                    if let Ok(hwnd) = window.hwnd() {
                        apply_native_rounded_corners(hwnd.0 as isize);
                    }
                }
            }

            // Ícone na bandeja do sistema com menu (Mostrar / Sair) — permite
            // reabrir o app quando ele estiver minimizado em segundo plano.
            use tauri::menu::{Menu, MenuItem};
            use tauri::tray::TrayIconBuilder;
            let show_item = MenuItem::with_id(app, "show", "Mostrar FluxTweakers", true, None::<&str>)?;
            let quit_item = MenuItem::with_id(app, "quit", "Sair", true, None::<&str>)?;
            let tray_menu = Menu::with_items(app, &[&show_item, &quit_item])?;
            let default_icon = app.default_window_icon().cloned();
            let mut tray_builder = TrayIconBuilder::new()
                .menu(&tray_menu)
                .tooltip("FluxTweakers")
                .on_menu_event(|app, event| {
                    match event.id.as_ref() {
                        "show" => {
                            if let Some(w) = app.get_webview_window("main") {
                                let _ = w.show();
                                let _ = w.set_focus();
                            }
                        }
                        "quit" => { app.exit(0); }
                        _ => {}
                    }
                })
                .on_tray_icon_event(|tray, event| {
                    if let tauri::tray::TrayIconEvent::Click {
                        button: tauri::tray::MouseButton::Left,
                        button_state: tauri::tray::MouseButtonState::Up, ..
                    } = event {
                        let app = tray.app_handle();
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.show();
                            let _ = w.set_focus();
                        }
                    }
                });
            if let Some(icon) = default_icon {
                tray_builder = tray_builder.icon(icon);
            }
            let _tray = tray_builder.build(app)?;

            // Intercepta o clique no X: se "minimizar pra bandeja" estiver ligado,
            // só esconde a janela em vez de fechar o app de verdade.
            if let Some(window) = app.get_webview_window("main") {
                let app_handle = app.handle().clone();
                window.on_window_event(move |event| {
                    if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                        let state = app_handle.state::<CloseBehaviorState>();
                        let should_hide = *state.0.lock().unwrap();
                        if should_hide {
                            api.prevent_close();
                            if let Some(w) = app_handle.get_webview_window("main") {
                                let _ = w.hide();
                            }
                        }
                    }
                });
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("erro ao rodar o app By Dgeras");
}


