// This file was auto-generated by scaffolding but is being written fresh here.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::fs;
use std::process::Command;

#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;

#[cfg(target_os = "windows")]
const CREATE_NO_WINDOW: u32 = 0x08000000;

/// Recebe o texto do .bat gerado pelo painel, salva num arquivo temporário
/// e executa TOTALMENTE ESCONDIDO (sem console piscando, sem downloads).
/// O único aviso que aparece pro usuário é o próprio UAC do Windows pedindo
/// permissão de administrador — isso o sistema operacional exige e não dá
/// pra pular, mas fora isso roda tudo em segundo plano dentro do app.
#[tauri::command]
fn run_bat_script(script_text: String) -> Result<String, String> {
    let temp_dir = std::env::temp_dir();
    let file_name = format!("dgeras-run-{}.bat", uuid_like());
    let file_path = temp_dir.join(&file_name);

    fs::write(&file_path, script_text).map_err(|e| format!("Falha ao gravar script: {e}"))?;

    let path_str = file_path.to_string_lossy().to_string();

    // Usa o PowerShell só como "lançador" elevado: Start-Process com -Verb RunAs
    // dispara o UAC, e -WindowStyle Hidden garante que nenhuma janela de console
    // apareça enquanto o .bat roda por trás. -Wait espera o script terminar.
    let ps_launcher = format!(
        "Start-Process -FilePath 'cmd.exe' -ArgumentList '/c \"{path}\"' -Verb RunAs -WindowStyle Hidden -Wait",
        path = path_str.replace('\'', "''")
    );

    #[cfg(target_os = "windows")]
    let result = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn();

    #[cfg(not(target_os = "windows"))]
    let result = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &ps_launcher])
        .spawn();

    match result {
        Ok(_) => Ok("Ajustes aplicados com sucesso".to_string()),
        Err(e) => Err(format!("Falha ao executar script: {e}")),
    }
}

fn uuid_like() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{nanos:x}")
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(tauri::generate_handler![run_bat_script])
        .run(tauri::generate_context!())
        .expect("erro ao rodar o app By Dgeras");
}

